print("My name is Diya")
print (10+10)
print ("My age is " + str(4+5))
print ("My age using multiplication  is " + str(3*3))
print (" I learn from " + "repl.it")
print ( " I am awesome")
print ( "10*14= " +str (10*14))
print ( " I am in 4rth grade")
print ( " Today is Mother's Day ")
print (" I am going to make a cake")
print (" I am absolutely awsome!")
print ( " I learn" +" with Python ")
print ( " Father's day is in June or July")